---

- hosts: localhost
  vars:
    data:
      - user0
      - user1
      - user2

  tasks:
    - name: "with_items"
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ data }}"
