---

- hosts: localhost

  tasks:
    - name: Create ec2 vm
      amazon.aws.ec2_instance:
        name: "{{ vm_name }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        region: "{{ region_name }}"
      register: vm_info

    - name: Print ec2 vm
      ansible.builtin.debug:
        var: vm_info

    - name: Add IP to inventory
      awx.awx.host:
        name: "{{ vm_info.vm_info.instances.public_ip_address }}"
        inventory: inventory_aws
        state: present

    - name: Add host to hostgroup
      awx.awx.group:
        name: tnode
        inventory: inventory_aws
        hosts:
          - "{{ vm_info.vm_info.instances.public_ip_address }}"
        preserve_existing_hosts: True

