---
# handlers file for myrole.nfs-server

- name: Restart NFS Service
  ansible.builtin.service:
    name: nfs-server
    state: restarted

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
